ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}

#FROM docker.elastic.co/elasticsearch/elasticsearch:7.2.1           指定版本可用，20190809測試ok版本為7.2.1


# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
