ARG ELK_VERSION

# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:${ELK_VERSION}

#FROM docker.elastic.co/kibana/kibana:7.2.1           指定版本可用，20190809測試ok版本為7.2.1

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
