ARG ELK_VERSION

# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}

#FROM docker.elastic.co/logstash/logstash:7.2.1           指定版本可用，20190809測試ok版本為7.2.1

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
